services:
- type: web
  name: saft-doctor
  env: docker
  plan: starter
  autoDeploy: true
  repo: https://github.com/CarlosJoao1/saft-doctor
  branch: main
  dockerfilePath: services/Dockerfile
  dockerContext: .
  envVars:
  - { key: APP_ENV, value: prod }
  - { key: DEFAULT_COUNTRY, value: pt }
  - { key: SECRET_KEY, sync: false }
  - { key: MASTER_KEY, sync: false }
  - { key: MONGO_URI, sync: false }
  - { key: MONGO_DB, value: saft_doctor }
  - { key: B2_ENDPOINT, value: https://s3.eu-central-003.backblazeb2.com }
  - { key: B2_REGION, value: eu-central-003 }
  - { key: B2_BUCKET, sync: false }
  - { key: B2_KEY_ID, sync: false }
  - { key: B2_APP_KEY, sync: false }
  - { key: FACTEMICLI_JAR_PATH, value: /opt/factemi/FACTEMICLI.jar }
  # If using Render Persistent Disk, mount it at /opt/factemi and place FACTEMICLI.jar there.
  # See Render docs. Ensure the path above matches the mount point.
  - { key: SUBMIT_TIMEOUT_MS, value: "600000" }
